config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :books do
   resource :favorites, only: [:create, :destroy]
   resources :book_comments, only: [:create, :destroy]
 end
  resources :users, only: [ :index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_to request.referer
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'Book was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: 'Book was successfully destroyed'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

private
def book_params
  params.require(:book).permit(:title, :body)
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render 'edit'
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render 'edit'
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<% if book.errors.any? %>
  <div class="error">
  <h2><%= book.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <td>
    <%= link_to book_favorites_path(book), method: :delete do %>
    <i class="fas fa-heart"></i>
    <%= book.favorites.count %>
  </td>
  <% end %>
<% else %>
  <td>
    <%= link_to book_favorites_path(book), method: :post do %>
    <i class="far fa-heart"></i>
    <%= book.favorites.count %>
  </td>
  <% end %>
<% end %>

app/views/books/_newbook.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book, local:true do |f| %>

<div class="field">
  <%= f.label :Title %>
  <%= f.text_field :title, class: "col-xs-12 book_title form-control" %>
</div>

<div class="field">
  <%= f.label :Opinion %>
  <%= f.text_area :body, class: "col-xs-12 book_body form-control" %>
</div>

<div class="actions">
  <%= f.submit 'Create Book', class: "btn btn-success col-xs-12" %>
</div>
<% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <%= render 'books/error', book: @book %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model:@book, local:true do |f| %>
      <div class="field">
        <%= f.label :Title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :Opinion %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="actions">
        <%= f.submit 'Update Book', class: "btn btn-success" %>
      </div>
      <%= link_to 'Show', book_path(@book.id) %>
      |
      <%= link_to 'Back', books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <%= render 'books/error', book: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: @user %>
      <%= render 'books/newbook', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <%= render 'books/favorite', book: book %>
            <td><p>コメント数: <%= book.book_comments.count %></p></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: @user %>
      <%= render 'books/newbook', book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %><br />
              <%= link_to @user.name, user_path(@user.id) %>
            </td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <%= render 'books/favorite', book: @book %>
            <td><p>コメント数: <%= @book.book_comments.count %></p></td>
            <% if @user.id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book.id), class: "btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table class="table">
        <% @book.book_comments.each do |book_comment| %>
          <tr>
            <td>
              <%= link_to user_path(book_comment.user) do %>
              <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size:'40x40' %><br>
              <%= book_comment.user.name %>
              <% end %>
            </td>
            <td><%= book_comment.comment %></td>
            <td>
              <% if book_comment.user == current_user %>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn-sm btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      <div>
      <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
      <div class="col-xs-12 comment-box">
        <%= f.text_area :comment, rows:'5', class: "form-control" %>
      </div>
        <%= f.submit "送信" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookres</strong>!
    </h1>  
  </div>
</div>

app/views/homes/top.html.erb
<p id=notice></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        Welcome to <i class="fas fa-book"></i>
        <strong>Bookers</strong> !!
      </h1>
      <p>
        In <i class="fas fa-book"></i>
        <strong>Bookers</strong>, 
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions<br />and various bokks!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/c7e949287a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <div class="container">
            <a class="navbar-brand" href="/"><span>Bookers</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <% if user_signed_in? %>
                <li>
                  <%= link_to ' Home', user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to ' Users', users_path, class: "fas fa-users nav-link text-light"  %>
                </li>
                <li>
                  <%= link_to ' Books', books_path, class: "fas fa-book-open nav-link text-light" %>
                </li>
                <li>
                  <%= link_to ' logout', destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
                </li>
                <% else %>
                <li>
                  <%= link_to ' Home', root_path, class: "fas fa-home nav-link text-light" %>
                </li>
                <li>
                  <%= link_to ' About', home_about_path, class: "fas fa-link nav-link text-light" %>
                </li>
                <li>
                  <%= link_to ' sign up', new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
                </li>
                <li>
                  <%= link_to ' login', new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
                </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <main>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
      <%= yield %>
      </main>
      <footer>
        <div class="container mt-5">
          <div class="row">
            <div class="mx-auto">
              <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </div>
      </footer>
  </body>
</html>

app/views/users/_userinfo.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 63, 63, format: 'jpeg', fallback: "no_image.jpg", size: '63x63' %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <% if @user.id == current_user.id %>
    <%= link_to '', edit_user_path(current_user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  <% else %>
    <%= link_to '', edit_user_path(user), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container"></div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
      <%= render 'books/error', book: @user %>
      <div class="field">
        <%= f.label :Name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :Image %>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>
      <div class="field">
        <%= f.label :Introduction %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="actions">
        <%= f.submit 'Update User', class: "btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: @user %>
      <%= render 'books/newbook', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %></td>
            <td><%= user.name %></td>
            <td><%= link_to 'Show', user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/userinfo', user: @user %>
      <%= render 'books/newbook', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
            <% @books.each do |book| %>
            <tr>
                <td>
                    <%= link_to user_path(@user.id) do %>
                    <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "attachment user profile_image fallback: no_image.jpg" %>
                    <% end %>
                </td>
                <td>
                    <%= link_to book_path(book) do %>
                    <%= book.title %>
                    <% end %>
                </td>
                <td><%= book.body %></td>
                <td><%= render 'books/favorite', book: book %></td>
                <td><p>コメント数: <%= book.book_comments.count %></p></td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>